DatabaseApplication/LostPassServer/Areas/AuthPage/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Http;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using LostPassServer.Areas.AuthPage.Models;

namespace LostPassServer.Areas.AuthPage.Controllers
{
    public class AuthController : Controller
    {
        public AuthController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public AuthController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; set; }

        //// GET: AuthPage/Auth
        //public ActionResult Index()
        //{
        //    return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        //}

        public ActionResult Login([Bind(Include = "Email,Password")] LoginModel lm)
        {
            return View(lm);
        }
        public ActionResult Register([Bind(Include = "Email,Password,ConfirmPassword")] RegisterModel rm)
        {
            return View(rm);
        }

        public ActionResult Reset()
        {
            return View();
        }

        public ActionResult Forgot()
        {
            return View();
        }
    }
}

DatabaseApplication/LostPassServer/Areas/MainPage/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Http;
using LostPassServer.Data;

namespace LostPassServer.Areas.MainPage.Controllers
{
    public class MainController : Controller
    {

        public MainController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public MainController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; set; }

        //// GET: MainPage/Main
        //public ActionResult Index()
        //{
        //    return View();
        //}

        public ActionResult About()
        {
            return View();
        }

        public ActionResult PasswordGenerator()
        {
            return View();
        }

        public ActionResult DeleteAccount()
        {
            return View();
        }

        public ActionResult Vault()
        {
           
            return View();
        }

        public ActionResult Configs()
        {

            return View();
        }

        public ActionResult Edit(int id)
        {
            using (var db = new dotNETDBEntities())
            {
                var pp = db.Pages.Where(p => p.PageID == id).Include("Passwords").First();
                return View(pp);
            }
        }


    }
}

DatabaseApplication/LostPassServer/Controllers/ConfigsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Http.Description;
using LostPassServer.Data;
using Microsoft.AspNet.Identity;

namespace LostPassServer.Controllers
{
    [Authorize]
    public class ConfigsController : ApiController
    {
        private dotNETDBEntities db = new dotNETDBEntities();

        // GET: api/Configs
        public async Task<IHttpActionResult> GetConfigs()
        {
            var name = User.Identity.GetUserId();
            var configs = await db.Configs.FindAsync(name);
            if (configs == null)
            {
                configs = new Configs()
                {
                    Username = name,
                    SortOrder = "Name - ascending"
                };
                db.Configs.Add(configs);
                await db.SaveChangesAsync();
            }
            return Ok(configs);
        }

        // GET: api/Configs/5
        [ResponseType(typeof(Configs))]
        public async Task<IHttpActionResult> GetConfigs(string id)
        {
            Configs configs = await db.Configs.FindAsync(id);
            if (configs == null)
            {
                return NotFound();
            }

            return Ok(configs);
        }

        // PUT: api/Configs/5
        [ResponseType(typeof(void))]
        public async Task<IHttpActionResult> PutConfigs(string id, Configs configs)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != configs.Username || id != User.Identity.GetUserId())
            {
                return BadRequest();
            }
            
            db.Entry(configs).State = EntityState.Modified;

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ConfigsExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return StatusCode(HttpStatusCode.NoContent);
        }

        // POST: api/Configs
        [ResponseType(typeof(Configs))]
        public async Task<IHttpActionResult> PostConfigs(Configs configs)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
           // await DeleteConfigs(configs.Username);
            db.Configs.Add(configs);

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateException)
            {
                if (ConfigsExists(configs.Username))
                {
                    return Conflict();
                }
                else
                {
                    throw;
                }
            }

            return CreatedAtRoute("DefaultApi", new { id = configs.Username }, configs);
        }

        // DELETE: api/Configs/5
        [ResponseType(typeof(Configs))]
        public async Task<IHttpActionResult> DeleteConfigs(string id)
        {
            Configs configs = await db.Configs.FindAsync(id);
            if (configs == null)
            {
                return NotFound();
            }

            db.Configs.Remove(configs);
            await db.SaveChangesAsync();

            return Ok(configs);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool ConfigsExists(string id)
        {
            return db.Configs.Count(e => e.Username == id) > 0;
        }
    }
}

DatabaseApplication/LostPassServer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width"/>
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="~/Content/bootstrap-table.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-contextmenu/2.4.2/jquery.contextMenu.css"/>
    <style>
        .right {
            float: right;
            margin: 4px;
        }
        .body-content {
            margin-bottom: 100px;
        }

        footer {
            
            padding: 1rem;
            background-color: #efefef;
            text-align: center;
        }

        img { margin-right: 5px; }

        
        /*#cont {
    width: 200px;
    height: 200px;
    border: 1px solid #aaa; 
        }*/



    </style>
</head>

<body>

<div class="navbar navbar-inverse navbar-fixed-top" id="nbar">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("LostPass", "Index", "Home", new {area = ""}, new {@class = "navbar-brand", accesskey = "H"})
        </div>
        <div class="navbar-collapse collapse">
            
            <ul class="nav navbar-nav navbar-right">
                @if (!Request.IsAuthenticated)
                {
                    <li>@Html.ActionLink("Log in", "Login", "Auth", new {area = "AuthPage"}, new { accesskey = "I" })</li>
                    <li>@Html.ActionLink("Sign up", "Register", "Auth", new {area = "AuthPage"}, new { accesskey = "S" })</li>
                }
                else
                {

                    <li>@Html.ActionLink("About", "About", "Main", new { area = "MainPage" }, new { accesskey = "A"} )</li>
                    <li>@Html.ActionLink("Delete Account", "DeleteAccount", "Main", new { area = "MainPage" }, new { accesskey = "D" })</li>
                    <li>@Html.ActionLink("Password Generator", "PasswordGenerator", "Main", new { area = "MainPage" }, new { accesskey = "P" })</li>
                    <li>@Html.ActionLink("Settings", "Configs", "Main", new { area = "MainPage" }, new { accesskey = "S" })</li>
                    <li>
                        <a href="#" id="Logout" accesskey="O">Log out</a>
                    </li>
                 
                }


            </ul>
        </div>
    </div>
</div>

<div class="container body-content">

    @RenderBody()


</div>
    
    <footer class="footer navbar-fixed-bottom">
       
        <p>This page uses brownies and we must inform you because if we don't, the EU will sue us.</p>

        <p>&copy; @DateTime.Now.Year - LostPass</p>
    </footer>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-contextmenu/2.4.2/jquery.contextMenu.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.8.1/bootstrap-table.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.8.1/locale/bootstrap-table-en-US.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.6/highlight.min.js"></script>
@if (Request.IsAuthenticated)
{
    <script>

        function copyToClipboard(text) {
            window.prompt("Copy to clipboard: Ctrl+C, Enter", text);
           
        }

        var setNavBarColor = function () {
            if (configs.ColorPalette)
                document.getElementById("nbar").style.background = "white";
       };

        var pages = [];
        var configs;
        var Edit = function(ind) {
            window.location = window.location + "/MainPage/Main/Edit/" + pages[ind].PageID;
        };
        var Delete = function(ind) {
            var token = localStorage.getItem("tokenInfo");
            var headers = {};

            if (token) {
                headers.Authorization = 'Bearer ' + token;
            }

            $.ajax({
                type: 'DELETE',
                url: '/api/pages/' + pages[ind].PageID,
                headers: headers
            }).success(function(data) {
                refreshTable(headers);
            });
        }


        function extractDomain(url) {
            var domain;
            //find & remove protocol (http, ftp, etc.) and get domain
            if (url.indexOf("://") > -1) {
                domain = url.split('/')[2];
            } else {
                domain = url.split('/')[0];
            }

            //find & remove port number
            domain = domain.split(':')[0];

            return domain;
        }

        function getFavIcon(url) {
            var dom = extractDomain(url);
            return "http://www.google.com/s2/favicons?domain=" + dom;
        }

        var changeOrder = function (data) {

        }


        function sortJSON(data, key, way) {
            return data.sort(function (a, b) {
                var x = a[key]; var y = b[key];
                if (way === 'asc') { return ((x < y) ? -1 : ((x > y) ? 1 : 0)); }
                if (way === 'desc') { return ((x > y) ? -1 : ((x < y) ? 1 : 0)); }
            });
        }



        var refreshTable = function (headers) {
            
            $.ajax({
                type: 'GET',
                url: '/api/configs',
                headers: headers
            }).success(function (data) {
                configs = data;

            }).fail(function (jqXHR, textStatus, error) {
                var response = jqXHR.responseText;
                alert('Error: ' + error + " " + "\n" + textStatus.error + "\n" + response);
            });


            $.ajax({
                type: 'GET',
                url: '/api/pages',
                headers: headers
            }).success(function (data) {
                if (configs.SortOrder == 'Name - ascending')
                    data = sortJSON(data, 'Name', 'asc');
                else if (configs.SortOrder == 'Name - descending')
                    data = sortJSON(data, 'Name', 'desc');
                else if (configs.SortOrder == 'Time Added (newest first)')
                    data = data.reverse();
                else if (configs.SortOrder == 'Time Added (oldest first)')
                    data = data;

                pages = data;
                
                $("#tbd").empty();

                for (var i = 0; i < data.length; i++) {
                    var t = data[i];
                    var passwd;

                    if (configs.HidePasswords)
                        passwd = Array(t.Passwords[0].Password.length + 1).join('•');
                    else
                        passwd = t.Passwords[0].Password;
                
                        $("#tbd").append("<tr><td><div>" +
                            '<img height=\"16\" width=\"16\" src="' +
                            getFavIcon(t.Name) +
                            '" /><a href="//' +
                            t.Name +
                            '" rel="external nofollow" >' +
                            t.Name +
                            '</a></div></td><td>' +
                            t.Passwords[0].Login +
                            "</td><td>" +
                        
                             passwd +
                        
                            "</td></tr>");
                    }


               
                $('#tbl').bootstrapTable({});
                $("#tbd").contextMenu({
                    selector: "tr",
                    callback: function(itemKey, opt) {
                        if (itemKey === "edit")
                            Edit($(this).closest('tr').prevAll().length);
                        if (itemKey === "delete")
                            Delete($(this).closest('tr').prevAll().length);
                        if (itemKey == 'copy') {
                            copyToClipboard(pages[$(this).closest('tr').prevAll().length].Passwords[0].Password);
                        }
                    },
                    items: {
                        "edit": { name: "Edit", icon: "edit" },
                        "copy": {name: "Copy password", icon: "copy"},
                        "delete": { name: "Delete", icon: "delete" },


                    }
                });
            }).fail(function(jqXHR, textStatus, error) {
                var response = jqXHR.responseText;

                alert('Error: ' + error + " " + "\n" + textStatus.error + "\n" + response);
            });
        }

        $(document).ready(function() {
            var token = localStorage.getItem("tokenInfo");
            var headers = {};

            if (token) {
                headers.Authorization = 'Bearer ' + token;
            }
            refreshTable(headers);
            window.setTimeout(setNavBarColor, 1000);
          
               
        });
        
        $("#search").on("keyup",
            function() {
                var value = $(this).val();

                $("table tr").each(function(index) {
                    if (index !== 0) {

                        $row = $(this);

                        var id = $row.find("td:first").text();

                        if (id.indexOf(value) < 0) {
                            $(this).hide();
                        } else {
                            $(this).show();
                        }
                    }
                });
            });

    </script>
}

<script>
    $('#Logout').click(function(e) {
        var token = sessionStorage.getItem("tokenInfo");
        var headers = {};
        if (token) {
            headers.Authorization = 'Bearer ' + token;
        }

        $.ajax({
            type: 'GET',
            url: 'api/account/logout',
            headers: headers
        }).done(function(data) {
            window.location = window.location.origin;
        }).fail(function(jqXHR, textStatus, error) {
            var response = JSON.parse(jqXHR.responseText);

            alert('Error: ' + error + " " + "\n" + textStatus.error + "\n" + response);
        });
        e.preventDefault();
        localStorage.removeItem("tokenInfo");
        document.cookie = ".AspNet.Cookies=; Path=/; expires=Thu, 01 Jan 1970 00:00:01 GMT;";

    });
</script>


</body>
</html>